app/views/dept_admin.py
"""
Provides administrators with a way to export scheduler data.
"""

# Third party imports
from flask import (Blueprint,
                   render_template,
                   current_app,
                   request,
                   jsonify)
from flask_cas import login_required
from boto3.dynamodb.conditions import Attr

# Local application imports
from app.users import User
from app.logger import DynamoAccessLogger
from app.extensions import dynamo
from app.utils.scheduler import get_local_ISO_timestamp

bp = Blueprint('dept_admin', __name__, url_prefix='/dept_admin')
logger = DynamoAccessLogger('dept_admin')


# ROUTES
@bp.route('/')
@login_required
def index():

    current_user = User()
    if current_user.is_dept_admin():

        table_name = current_app.config['DB_SCHEDULING']
        resp_events = dynamo.tables[table_name].query(
            IndexName='start-index',
            KeyConditionExpression='PK = :pk',
            ExpressionAttributeValues={
                ':pk': f'EVENT#{current_user.dept}',
            },
        )

        logger.log_access(success=True, route='booking_list')
        return render_template('dept_admin.html', events=resp_events['Items'])

    else:

        logger.log_access(success=False, route='booking_list')
        return render_template('403.html')


@bp.route('/user_management')
@login_required
def user_management():

    current_user = User()
    if current_user.is_dept_admin():

        table_name = current_app.config['DB_SCHEDULING']
        resp_users = dynamo.tables[table_name].query(
            IndexName='reverse-index',
            KeyConditionExpression='SK = :sk AND PK > :pk',
            ExpressionAttributeValues={
                ':sk': current_user.dept,
                ':pk': 'USER',
            },
        )

        logger.log_access(success=True, route='user_management')
        return render_template('user_management.html', users=resp_users['Items'])

    else:

        logger.log_access(success=False, route='user_management')
        return render_template('403.html')


def add_users(add_list):
    """
    Adds users after parsing the input. Errors are reported as string messages.
    """
    table_name = current_app.config['DB_SCHEDULING']
    table = dynamo.tables[table_name]
    connection = dynamo.connection

    current_user = User()
    dept = current_user.dept

    success = 0
    errors = []

    if add_list:
        try:
            with table.batch_writer() as batch:
                for user in add_list:
                    if user.strip():
                        user_params = dict(zip(('uni', 'first_name', 'last_name', 'type'), [s.strip() for s in user.split(',')]))
                        if not user_params.get('uni'):
                            errors.append(f'{user}\n')
                            continue
                        try:
                            user_item = {
                                'PK': f"USER#{user_params.get('uni').lower()}",
                                'SK': dept,
                                'last_name': user_params.get('last_name', ''),
                                'first_name': user_params.get('first_name', ''),
                                'type': user_params.get('type', ''),
                                'added_by': current_user.uni,
                                'added_on': get_local_ISO_timestamp()
                            }
                            batch.put_item(Item=user_item)
                            success += 1
                        except Exception:
                            errors.append(f'{user}\n')
        except connection.meta.client.exceptions.ClientError:
            return 'Unexpected error when adding.'

    output = f'Added {success} user(s).'
    if errors:
        output = f"{output}\nUNABLE TO ADD THE FOLLOWING LINES:\n{''.join(errors)}"

    return output


def remove_users(remove_list):
    """
    Removes users listed in the input. Errors are reported as string messages.
    User's PK needs exists in the table, otherwise reported as error.
    """
    table_name = current_app.config['DB_SCHEDULING']
    table = dynamo.tables[table_name]
    connection = dynamo.connection

    current_user = User()
    dept = current_user.dept

    success = 0
    errors = []

    if remove_list:
        try:
            for user in remove_list:
                if user.strip():
                    try:
                        user_item = {
                            'PK': f'USER#{user.lower()}',
                            'SK': dept
                        }
                        # Only delete user its PK exists
                        table.delete_item(Key=user_item, ConditionExpression=Attr('PK').exists())
                        success += 1
                    except Exception:
                        errors.append(f'{user}\n')
        except connection.meta.client.exceptions.ClientError:
            return 'Unexpected error when removing.'

    output = f'Removed {success} user(s).'
    if errors:
        output = f"{output}\nUNABLE TO REMOVE THE FOLLOWING UNIS:\n{''.join(errors)}"

    return output


@bp.route('/user_management/batch', methods=['POST'])
@login_required
def process_batch():
    """
    Input from two text fields are sent to this route for processing. HTML's <textarea>'s newlines are '\r\n'
    """

    current_user = User()
    if current_user.is_dept_admin():

        add_list = set(request.form['add'].split('\r\n')) if request.form['add'] else []
        remove_list = set(request.form['remove'].split('\r\n')) if request.form['remove'] else []

        add_output = add_users(add_list)
        remove_output = remove_users(remove_list)

        output_str = f'{add_output}\n{remove_output}'
        logger.log_access(success=True, route='user_management_batch')
        return jsonify(output=output_str), 200

    else:

        logger.log_access(success=False, route='user_management_batch')
        return render_template('403.html')

app/views/scheduler.py
"""
Scheduler
"""
# Standard library imports
from uuid import uuid4
from operator import itemgetter

# Third party imports
from flask import (Blueprint,
                   render_template,
                   request,
                   redirect,
                   url_for,
                   current_app,
                   abort,
                   jsonify)
from flask.json import dumps as json_dumps
from flask_cas import login_required

from boto3.dynamodb.conditions import Attr
from itsdangerous.exc import BadSignature

# Local application imports
from app.users import User
from app.logger import DynamoAccessLogger
from app.extensions import dynamo

from app.utils.scheduler import (decimal_conversion,
                                 datetime_to_EST,
                                 get_local_ISO_timestamp,
                                 is_overlapping,
                                 natmultisort)

bp = Blueprint('scheduler', __name__)
logger = DynamoAccessLogger('room_scheduler')


# ROUTES
@bp.route('/')
@login_required
def index():
    current_user = User()
    dept = current_user.dept

    if dept:

        logger.log_access(success=True, route='index')

        table_name = current_app.config['DB_SCHEDULING']
        resp_events = dynamo.tables[table_name].query(
            IndexName='uni-PK-index',
            KeyConditionExpression='uni = :uni AND PK = :pk',
            ExpressionAttributeValues={
                ':uni': current_user.uni,
                ':pk': f'EVENT#{dept}',
            },
        )

        # Sort by start time
        events = sorted(resp_events['Items'], key=itemgetter('start'))
        return render_template('scheduler.html', events=events)

    else:

        logger.log_access(success=False, route='index')
        return render_template('403.html')


@bp.route('/event_data')
def event_data():
    """
    Returns all existing event and blocked-off times for the user's department
    """
    if not ('start' in request.args and 'end' in request.args):
        logger.log_access(success=False, route='event_data', error='RequestArgs')
        return redirect(url_for('scheduler.index'))

    current_user = User()

    table_name = current_app.config['DB_SCHEDULING']
    resp_events = dynamo.tables[table_name].query(
        IndexName='start-index',
        KeyConditionExpression='PK = :pk AND #s BETWEEN :lower AND :upper',
        ExpressionAttributeValues={
            ':pk': f'EVENT#{current_user.dept}',
            ':lower': f"{request.args.get('start')}",
            ':upper': f"{request.args.get('end')}",
        },
        ExpressionAttributeNames={
            '#s': 'start',
        },
        FilterExpression=Attr('active').eq(True)
    )

    resp_notavailable = dynamo.tables[table_name].query(
        KeyConditionExpression='PK = :pk',
        ExpressionAttributeValues={
            ':pk': f'BLOCK#{current_user.dept}',
        },
    )

    resp_events['Items'].extend(resp_notavailable['Items'])

    # Dynamo returns numbers as Decimal objects, convert to integers with the default functions
    return json_dumps(resp_events['Items'], default=decimal_conversion)


@bp.route('/resource_data', methods=['POST'])
def resource_data():
    """
    Returns all resources for the user's department
    """
    current_user = User()

    table_name = current_app.config['DB_SCHEDULING']
    resp_resources = dynamo.tables[table_name].query(
        KeyConditionExpression='PK = :pk',
        ExpressionAttributeValues={
            ':pk': f'RESOURCE#{current_user.dept}',
        },
    )

    # Use natural sorting to make sure 900 comes before 1000, etc.
    return jsonify(natmultisort(resp_resources['Items'], (('room', False), ('title', False))))


@bp.route('/event_modify', methods=['POST'])
def event_modify():
    """
    Application logic for moving an event to a different time/day/resource.
    Called by `eventResize` and `eventDrop` fullcalendar callbacks

    Payload should contain the following attributes:
        PK: Primary key of the event,
        SK: Sort key of the event,
        uni: Event owner's uni,
        start: Start time of the modified event,
        end: End time of the modified event

    If the event is moved to a new resource, the payload should also contain:
        newResourceId: Resource ID of the modified event,
        newResourceName: Resource name of the modified event
    """

    data = request.json
    current_user = User()

    if data['uni'] != current_user.uni:
        logger.log_access(success=False, route='event_modify', error='NotOwnReservation')
        return 'You can only modify your own reservations.', 403

    expr = 'SET #s = :s, #e = :e, changedOn = :t'
    vals = {
        ':s': data['start'],
        ':e': data['end'],
        ':t': get_local_ISO_timestamp(),
    }

    if 'newResourceId' in data:
        expr = f'{expr}, resourceId = :r, resourceName = :n'
        vals[':r'] = data['newResourceId']
        vals[':n'] = data['newResourceName']

    try:
        table_name = current_app.config['DB_SCHEDULING']
        dynamo.tables[table_name].update_item(
            Key={'PK': data['PK'], 'SK': data['SK']},
            UpdateExpression=expr,
            ExpressionAttributeValues=vals,
            ExpressionAttributeNames={
                '#s': 'start',
                '#e': 'end',
            }
        )
    except Exception as e:
        print(e)
        return 'Unexpected error occured', 500

    logger.log_access(success=True, route='event_modify')
    return 'Success', 200


@bp.route('/event_create', methods=['POST'])
def event_create():
    """
    Application logic for creating an event.
    Called by the `select` fullcalendar callback.

    Payload should contain the following attributes:
        - start: event start timestamp
        - end: event end timestamp
        - resourceId: id of the resource where event was scheduled
        - resourceName: name of the resource where event was scheduled
        - viewStart: the start of the interval the calendar currently represents
        - viewEnd: the end of the interval the calendar currently represents

    viewStart and viewEnd are used to check for overlapping events by getting all
    events between the two timestamps for the resourceId. They are in UTC time so
    they are first converted to EDT/EST.

    If no overlaps are present, event metadata is recorded to DynamoDB.
    """

    table_name = current_app.config['DB_SCHEDULING']
    current_user = User()
    uni = current_user.uni
    dept = current_user.dept

    request_data = request.json
    resourceId = request_data.get('resourceId')
    event_start = request_data.get('start')
    event_end = request_data.get('end')

    view_start = datetime_to_EST(request_data['viewStart'])
    view_end = datetime_to_EST(request_data['viewEnd'])

    resp_events_view = dynamo.tables[table_name].query(
        IndexName='resourceId-start-index',
        KeyConditionExpression='resourceId = :r AND #s BETWEEN :lower AND :upper',
        ExpressionAttributeValues={
            ':r': resourceId,
            ':lower': view_start,
            ':upper': view_end,
        },
        ExpressionAttributeNames={
            '#s': 'start',
        },
        FilterExpression=Attr('active').eq(True)
    )

    if (is_overlapping(resp_events_view['Items'], request_data)):
        logger.log_access(success=False, route='event_create', error='Overlap')
        return 'Your booking overlaps with another booking or a reserved time.', 500

    item = {
        'PK': f'EVENT#{dept}',
        'SK': f"{request_data.get('resourceId')}#{uuid4()}",
        'start': event_start,
        'end': event_end,
        'resourceId': resourceId,
        'resourceName': request_data.get('resourceName'),
        'title': uni,
        'uni': uni,
        'active': True,
        'createdOn': get_local_ISO_timestamp(),
        'changedOn': '',
        'dept': dept,
    }

    try:
        dynamo.tables[table_name].put_item(Item=item)
    except Exception:
        logger.log_access(success=False, route='event_create', error='Unexpected 500')
        return 'Unexpected error occured', 500

    logger.log_access(success=True, route='event_create')
    return 'Success', 200


@bp.route('/event_delete', methods=['POST'])
def event_delete():
    """
    Application logic for deleting an event.
    """

    s = current_app.config['SERIALIZER']

    try:
        PK = s.loads(request.form['PK'])
        SK = s.loads(request.form['SK'])
    except BadSignature:
        logger.log_access(success=False, route='event_delete', error='BadSignature')
        abort(400)

    try:
        table_name = current_app.config['DB_SCHEDULING']
        dynamo.tables[table_name].update_item(
            Key={'PK': PK, 'SK': SK},
            UpdateExpression='SET active = :f, changedOn = :t',
            ExpressionAttributeValues={
                ':f': False,
                ':t': get_local_ISO_timestamp(),
            }
        )
    except Exception:
        logger.log_access(success=False, route='event_delete', error='Unexpected 500')
        return 'Unexpected error occured', 500

    logger.log_access(success=True, route='event_delete')
    return redirect(url_for('scheduler.index', _anchor='history'))


@bp.route('/ping')
def ping():
    """
    ELB health checks fail because accessing the root of the app redirects to CAS login.
    This route simply returns the 200 code for the health check
    """
    return 'Success', 200

app/templates/admin.html
{%- extends "base.html" %}
{%- block title %}Room Scheduler{%- endblock title %}

{%- block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@5.2.0/main.min.css" integrity="sha256-LOn2s1oZo044zPt6G3x2mGJnhtfXp6ZE1skHztfqnA8=" crossorigin="anonymous">
{{ super() }}
{%- endblock %}

{%- block content %}
<script>
const options = {
    schedulerLicenseKey: '0320620453-fcs-1597083069',
    aspectRatio: 1.7,
    editable: true,
    selectable: true,
    nowIndicator: true,
    themeSystem: 'bootstrap',
    timeZone: 'local',
    headerToolbar: {
        left: 'today prev,next',
        center: 'title',
        right: 'resourceTimelineDay,resourceTimelineWeek'
    },
    views: { 
        day: { // customize day view to show weekday
            titleFormat: { weekday: 'short', month: 'short', day: 'numeric' }
        },
        week: { // customize week view to exclude year
            titleFormat: { month: 'short', day: 'numeric' }
        }
    },
    initialView: 'resourceTimelineDay',
    resourceAreaHeaderContent: 'Room',
    resourceGroupField: 'room',
    resourceAreaWidth: '25%',
    resourceOrder: 'PK',  // Sorting by this, which is the same for all resources, will ensure fullcalendar does not mess up the correct order from url feed
    resources: {
        url: 'resource_data',
        method: 'POST'
    },
    events: {
        url: 'event_data',
        failure: function() {
            alert('Unexpected error while fetching events.');
        },
    },
    eventOverlap: false,
    firstDay: 1, // start week on Sunday
}

document.addEventListener('DOMContentLoaded', function() {

    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, options);
    calendar.render();

});
</script>

<div id="calendar" class="my-3"></div>
{%- endblock %}

{%- block scripts %}
    {{ super() }}
    <script src="https://cdn.jsdelivr.net/npm/moment@2.27.0/moment.js" integrity="sha256-QTriwEK1XTUJdKp3So7tMDUvZSTLOPpUv8F/J+UwJ8M=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@5.2.0/main.min.js" integrity="sha256-U+VlpMlWIzzE74RY4mZL4MixQg66XWfjEWW2VUxHgcE=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/moment@5.2.0/main.global.min.js" integrity="sha256-7WNMw3NoYwwtQzbvaebEKKhPHwqVf3kKGfSHTf18qdg=" crossorigin="anonymous"></script>
{%- endblock %}

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
{%- block head %}
{%- if config['ENV'] == 'prod' %}
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-145333546-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-145333546-3');
</script>
{%- endif %}
<title>{%- block title %}A&S Reporting{%- endblock title %}</title>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="robots" content="noindex, nofollow">

<!-- Favicon -->
<link rel="shortcut icon" href="https://cu-dash-static.s3.us-east-2.amazonaws.com/img/favicon.png" type="image/x-icon">
<link rel="icon" href="https://cu-dash-static.s3.us-east-2.amazonaws.com/img/favicon.png" type="image/x-icon">

{%- block css %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/cerulean/bootstrap.min.css" integrity="sha384-3fdgwJw17Bi87e1QQ4fsLn4rUFqWw//KU0g8TvV6quvahISRewev6/EocKNuJmEw" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
<style>
.container, .container-sm, .container-md {
    max-width: 90%;
}
</style>
{%- endblock css %}
{%- endblock head %}
</head>

<body>
{%- block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<div class="container">
    <a class="navbar-brand mb-0 h1" href="/">
        <img src="https://cu-dash-static.s3.us-east-2.amazonaws.com/img/crown-white.png" height="30" class="d-inline-block align-top mr-2">A&S Rooms
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
        {%- block navlinks %}
        {% if session.CAS_USERNAME | user_is_dept_admin %}
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown">
                    Dept. Admin
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{{ url_for('dept_admin.index') }}">Booking List</a>
                    <a class="dropdown-item" href="{{ url_for('dept_admin.user_management') }}">User Management</a>
                </div>
            </li>
        </ul>
        {% endif %}
        {%- endblock %}
        {% if 'CAS_USERNAME' in session %}
            <span class="navbar-text ml-auto">
                Signed in as {{ session.CAS_USERNAME }} 
            </span>
            <form class="form-inline my-2 my-lg-0" action="{{ url_for('cas.logout') }}">
                <button class="btn btn-secondary my-2 ml-2 my-sm-0">Logout</button>
            </form>
        {% endif %}
     </div>

</div>
</nav>
{%- endblock navbar %}

<div class="container">
{%- block content %}
{%- endblock content %}
</div>

{%- block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{%- endblock scripts %}

</body>
</html>

app/templates/scheduler.html
{%- extends "base.html" %}
{%- block title %}Room Scheduler{%- endblock title %}

{%- block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@5.2.0/main.min.css" integrity="sha256-LOn2s1oZo044zPt6G3x2mGJnhtfXp6ZE1skHztfqnA8=" crossorigin="anonymous">
{{ super() }}
{%- endblock %}

{%- block content %}
<div class="my-4">
    <p><b>Please be courteous and respectful of your fellow students in following the guidelines below:</b></p>
    <ul>
        <li>Wear a mask at all times, unless you are in a private office with the door closed. (A mask may be removed for short durations to eat or drink, provided you are more than 6 feet away from the nearest person.)</li>
        <li>Maintain 6 feet of physical distance.</li>
        <li>Posted maximum occupancies must be maintained at all times.</li>
        <li>Shared surfaces should be wiped down by the user before and after use.</li>
        <li>Furniture must not be moved.</li>
    </ul>   
    <b>Instructions:</b> Please switch to landscape on mobile. Click and drag on the calendar to create a reservation for yourself. The title of your reservation will be your UNI, visible to all students in your home department who have access to this calendar. Drag or resize an existing reservation created by you to modify it. To delete a reservation, see the table at the bottom of the page. You cannot undelete a reservation, create a new one instead. If you encounter issues with the calendar, please reach out to <a href="mailto:tg2648@columbia.edu">Timur Gulyamov</a>. For all other questions, please reach out to your department DAAF.
</div>

<div id="calendar"></div>

<h5 class="text-info my-4" id="history">Reservation History:</h3>
<table class="table table-hover">
    <thead>
        <tr>
        <th scope="col">Location</th>
        <th scope="col">Start</th>
        <th scope="col">End</th>
        <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for e in events %}
        <tr>        
            <th scope="row" {% if not e['active'] %} class='text-muted font-italic' {% endif %}>{{ e['resourceName'] }}</th>
            <td {% if not e['active'] %} class='text-muted font-italic' {% endif %}>{{ e['start'] | datetime_humanize }}</td>
            <td {% if not e['active'] %} class='text-muted font-italic' {% endif %}>{{ e['end'] | datetime_humanize }}</td>
            {% if e['active'] %}
            <td class="text-center">
                <form class="download-form" action="{{ url_for('scheduler.event_delete') }}" method="POST">
                    <input type="hidden" name="PK" value="{{ e['PK'] | serialize }}">
                    <input type="hidden" name="SK" value="{{ e['SK'] | serialize }}">
                    <button type="submit" class="btn btn-danger btn-sm">
                      <i class="fa fa-trash-o fa-lg"></i>
                    </button>
                </form>
            </td>
            {% else %}
            <td class="text-center text-muted font-italic">Deleted</td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>

{%- endblock %}

{%- block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='calendar.js') }}"></script>
    <script src="https://cu-dash-static.s3.us-east-2.amazonaws.com/scripts/idle.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/moment@2.27.0/moment.js" integrity="sha256-QTriwEK1XTUJdKp3So7tMDUvZSTLOPpUv8F/J+UwJ8M=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@5.2.0/main.min.js" integrity="sha256-U+VlpMlWIzzE74RY4mZL4MixQg66XWfjEWW2VUxHgcE=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/moment@5.2.0/main.global.min.js" integrity="sha256-7WNMw3NoYwwtQzbvaebEKKhPHwqVf3kKGfSHTf18qdg=" crossorigin="anonymous"></script>
{%- endblock %}

app/templates/user_management.html
{%- extends "base.html" %}
{%- block title %}Room Scheduler - User Management{%- endblock title %}

{%- block css %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.22/b-1.6.4/b-html5-1.6.4/r-2.2.6/sp-1.2.0/sl-1.3.1/datatables.min.css"/>
{%- endblock %}

{%- block content %}
<div class="my-4 row">
<div class="col-lg">
    <table id="users" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>UNI</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Type/Role</th>
            </tr>
        </thead>
        <tbody>
            {% for u in users %}
            <tr>
                <td>{{ u['PK'].split('#')[1] }}</td>
                <td>{{ u['first_name']}}</td>
                <td>{{ u['last_name']}}</td>
                <td>{{ u['type']}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="col-lg">
    <form id="batch">
        <div class="form-group">
            <label for="batch-add-input"><h4>Batch add</h4>Enter one user per line in the comma-separated format: UNI (required), first_name, last_name, type/role.<br><b>Example</b>: lcb50, Lee, Bollinger, President<br>You can use this <a href="https://drive.google.com/file/d/1elfqD4HibSu-gjWzVGzqZL-4ShscnfA_/view?usp=sharing">Excel template</a> to format many records at a time.<br><b>Note</b>: users with type/role of <u>Chair</u> or <u>Staff</u> receive access to department admin pages.</label>
            <textarea class="form-control" id="batch-add-input" name="add" rows="8"></textarea>
            <label for="batch-remove-input"><h4 class="mt-2">Batch remove</h4>Enter UNIs only, one per line</label>
            <textarea class="form-control" id="batch-remove-input" name="remove" rows="8"></textarea>
        </div>
        <button id="batch-btn" type="submit" class="btn btn-primary">Add/Remove Users</button>
    </form>
    <div id="batch-output" class="mt-2"></div>
</div>
</div>
{%- endblock %}

{%- block scripts %}
{{ super() }}
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.22/b-1.6.4/b-html5-1.6.4/r-2.2.6/sp-1.2.0/sl-1.3.1/datatables.min.js"></script>
<script>
    $(document).ready(function() {
        $('#users').DataTable({
            dom: '<"row"<"col-sm-12 col-md-2"B><"col-sm-12 col-md-3"l><"col-sm-12 col-md-7"f>>rt<"row"<"col-sm-12 col-md-5"i><"col-sm-12 col-md-7"p>>',
            responsive: true,
            pageLength: 10,
            buttons: [
                {
                    extend: 'csvHtml5',
                    text: 'Save as CSV',
                    title: 'Room_Booking_Users_Export_' + new Date().toISOString()
                },
            ]
        });
    } );
</script>
{%- block form_scripts %}
<script>
    function batchSubmit(event) {
        event.preventDefault();
        var request = new XMLHttpRequest();
        request.addEventListener('load', batchShow);
        request.open('POST', {{ url_for('dept_admin.process_batch') | tojson }});
        request.send(new FormData(this));
    }

    function batchShow() {
        var data = JSON.parse(this.responseText);
        var status = JSON.parse(this.status);
        var output = document.getElementById('batch-output');
        output.innerText = data.output;
    }
    
    var form = document.getElementById('batch');
    form.addEventListener('submit', batchSubmit);
</script>
{%- endblock %}
{%- endblock %}